---
abstract: 'run code after the response has been sent.'
author:
  - 'Matt S Trout (mst) <mst@shadowcat.co.uk>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Module::Find: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.87'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Plugin-RunAfterRequest
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst::Component::InstancePerContext: 0
  Catalyst::Controller: 0
  Catalyst::Runtime: 0
  Catalyst::Test: 0
  MRO::Compat: 0
  Moose: 0
  Moose::Role: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://dev.catalyst.perl.org/repos/Catalyst/Catalyst-Plugin-RunAfterRequest/trunk/
version: 0.02
